//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBIT.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientsRecord
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Dish_type { get; set; }
        public int No_of_Ingredients { get; set; }
        public string Ingredients { get; set; }
    }
}
